# CI
name: CI


on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#　　- name: Delete image
#    　uses: bots-house/ghcr-delete-image-action@v1.0.0
#      with:
#        # NOTE: at now only orgs is supported
#        owner: bots-house
#        name: ${GITHUB_REPOSITORY}/test_container:tmp
#        # NOTE: using Personal Access Token
#        token: ${{ secrets.GITHUB_TOKEN }}
##        tag: tmp
    - uses: actions/checkout@v1
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
#        registry: ${{ env.REGISTRY }}
        #username: okamototk
        username: ${{ github.actor }}
#        password: ${{ secrets.AUTH_TOKEN }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build Dockerfile and push image # userで外部ファイル or 定義済みの処理を実行できる。ここではリポジトリのcheckout
      run: |
#        IMAGE_NAME=test_container:${GITHUB_REF#refs/heads/} # docer imageの名前とそのタグ、${GITHUB_REF#refs/heads/}でブランチ名を取得している
        IMAGE_NAME=test_container:test # docer imageの名前とそのタグ、${GITHUB_REF#refs/heads/}でブランチ名を取得している
        docker build ./app -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}
    - uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
      env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }} # リポジトリのsecretsとして定義した値を環境変数に渡す
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
